### ISSUE TITLE
Cannot validate Record with `geometry=null`

### ISSUE THREAD

**Issue by SpeckiJ** [ogcincubator/bblocks-ogcapi-records#1]
When trying to validate a record with has `geometry:null`, validation fails as the `oneOf` that tries to match the geometry is matching multiple of the referenced schemata.

Example: 

https://www.jsonschemavalidator.net/s/qd5smIoV

The relevant lines are here: 

https://github.com/ogcincubator/bblocks-ogcapi-records/blob/f5b407ca894f55af4647f7c44e0f4065b6db7d9c/_sources/v1/schemas/recordGeoJSON/schema.yaml
```yaml
  geometry:
    oneOf:
      - enum:
        - null
      - $ref: bblocks://ogc.geo.common.data_types.geojson#/properties/geometry
```

where the referenced `$ref: bblocks://ogc.geo.common.data_types.geojson#/properties/geometry` can itself be null, but we specify that it can be null ourselves too.
